### ISSUE TITLE
Merge with fork

### ISSUE THREAD

**Issue by holocronweaver** [mehrdad-shokri/disable_battery_optimization#2]
It looks like there was [a fork](https://pub.dev/packages/optimize_battery) which adds "Null safety and Android V2 embedding". However the fork dropped iOS support. The fork's package name is also misleading, named "optimize battery" yet is actually about disabling battery optimization.

There is also a [pull request on this repo to migrate to null safety (#1).

In order to maintain iOS support and the clear name, I propose:
- [ ] migrate this repo to a shared Github Organization (perhaps [Flutter Community](https://github.com/fluttercommunity)) and grant access to a few other people (including the person who made the fork) to help maintain the package.
- [ ] merge the [fork](https://pub.dev/packages/optimize_battery) into this repo.
- [ ] merge #1 as well if it has bits not covered by the fork.

**Comment by holocronweaver** [comment]
@mehrdad-shokri I can help out with these tasks if you can grant me permissions, say by you completing the first task of migrating to a Github org.

**Comment by mehrdad-shokri** [comment]
Hello @holocronweaver, I created this fork a while ago where the original package didn't support null safety. Apparently it does now. Can you please check the original package repo to see if you have any problem with that package? https://github.com/Bhat015/optimize_battery

**Comment by holocronweaver** [comment]
Woops, I got it backwards, I thought this was the original package and `optimize_battery` was the fork.

A quick glance at both package sources seems to indicate neither support iOS - is this correct?

**Comment by mehrdad-shokri** [comment]
@holocronweaver to the extend that I know, this feature is only available on Android and there is no such thing on iOS.
